### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by ntimanu**

### CODE REVIEW

**Review by osamaashraf6 — CHANGES_REQUESTED** [review]
Hi @ntimanu 👋, 

Good job so far! 👏🥳
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

ItsJustATinyChangeSheaWhitneyGIF


## Highlights ✔️

- [x] No linter errors. 💯
- [x] Good usage in correcting GitHub flow




## Required Changes ♻️

- [ ] Kindly 😃use [the Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. The only optional section is a FAQ. Please remove the template logo on the top, if you have one, you can replace it. This is crucial to have a professional and instructive repository. 👌

- [ ] You did well 🎈🪄on the project, but I see that you didn't write a pull request for this project, so please😃 add a Pull Request which should have a descriptive title telling you what changes are inside and Pull Request should have a summary describing introduced changes in more detail.💯
- [ ]  Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, for example: "Add html file" instead of "add html file" ... etc 👍



## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by ntimanu** [comment]
How can I reopen this pull request!

**Comment by osamaashraf6** [comment]
> How can I reopen this pull request!

Hello @ntimanu  ☺️👏 I think you can not open it now ,but don't worry ,kindly  tell me when you try to make a pull request from the dashboard you can request or not

**Comment by ntimanu** [comment]
@osamaashraf6 Yes I can on the dashboard I have 2 request reviewer left.

**Comment by osamaashraf6** [comment]
> @osamaashraf6 Yes I can on the dashboard I have 2 request reviewer left.

,So  @ntimanu the problem with you now which you asking about it how to reopen the pull request or there is another problem?

**Comment by ntimanu** [comment]
@osamaashraf6 is it possible to change the link I submitted before because I have done another project and collect all changes that were required, but they are asking me to keep using the same project that I submitted at the first request reviewer.

**Comment by ntimanu** [comment]
> > @osamaashraf6 Yes I can on the dashboard I have 2 request reviewer left.
> 
> ,So @ntimanu the problem with you now which you asking about it how to reopen the pull request or there is another problem?

Yeah, that was the problem!

**Comment by osamaashraf6** [comment]
> > > @osamaashraf6 Yes I can on the dashboard I have 2 request reviewer left.
> > 
> > 
> > ,So @ntimanu the problem with you now which you asking about it how to reopen the pull request or there is another problem?
> 
> Yeah, that was the problem!

@ntimanu  I asked a person now about your case and the solution now is to add the changes which I requested from you at my review and deal with the merged pull request as open request leave it merged and submit it again after adding the changes.

**Pull request merged**
